# Generated by Django 4.2.2 on 2023-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
