# Generated by Django 4.2.2 on 2023-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_rename_age_employee_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthday',
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
