# Generated by Django 4.2.2 on 2023-06-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
