# Generated by Django 4.2.2 on 2023-06-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_store_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'verbose_name': 'StoreProduct',
                'verbose_name_plural': 'StoreProducts',
            },
        ),
    ]
