# Generated by Django 4.2.2 on 2023-06-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_storeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
