# Generated by Django 4.2.2 on 2023-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_alter_storeproduct_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m'),
        ),
    ]
