# Generated by Django 4.2.2 on 2023-06-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_storeproduct_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproduct',
            old_name='image',
            new_name='picture',
        ),
    ]
