# Generated by Django 4.2.2 on 2023-06-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_rename_image_storeproduct_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproduct',
            old_name='picture',
            new_name='image',
        ),
    ]
